
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 8426144

[crossroads]
	#The byproduct material to output in Crossroads' Millstone.
	byproduct = "minecraft:sand"

[silents_mechanisms]
	#The byproduct material to output in Silent's Mechanisms' Crusher.
	byproduct = "minecraft:cobblestone"

